name: Pytest

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: actions/checkout@v3

            - name: Set up python 3.10
            #uses: actions/setup-python@v4
            uses: actions/setup-python@v5
            with:
                python-version: '3.10'
                cache: 'pip'

            - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: Unit Tests
            run: |
                python -m pytest -m unit
            
            - name: Integration Tests
            run: |
                python -m pytest -m integration